### PR TITLE
Add get_distinct_mut method to SecondaryMap

### PR DESCRIPTION
**Pull request by michael-p**
`get_distinct_mut` allows one to get two mutable references to distinct values stored in a `SecondaryMap`, making various access patterns easier when the values are not `Copy` (this is a feature that is requested for the stdlib's `HashMap` over and over again).

Questions:
* Not 100% sure about the name. Maybe `get_pair_mut` or similar would be better?
* For "symmetry reasons" we should probably also implement this for the other maps as well? I did not do this because: 1) `SlotMap` requires its values to be `Copy` and so this wouldn't be really useful there, 2) `SparseSecondaryMap` is backed by a `HashMap` and hence implementation would require unsafe code, 3) I just haven't used `HopSlotMap` yet, so no idea there :)

### CODE REVIEW

**Comment by orlp** [comment]
This is indeed an access pattern that is very useful. I'm considering making the API even more general by supporting _n_ simultaneous key accesses.

**Comment by michael-p** [comment]
That would be even better, yes! I just chose the "path of least resistance" because I needed the functionality for another project :)

**Comment by michael-p** [comment]
@orlp Is there any chance of getting this merged? If you want me to change anything, write more docs, tests, etc please let me know! :)

**Comment by orlp** [comment]
Sorry I kinda forgot about this. I'm not going to merge this because I want to really be certain of the API first and introduce it across the board. Perhaps it will have to wait for const generics for `get_disjoint_mut([K; N]) -> Option<[&mut V; N]>`, which is the current API I'm leaning towards.

**Comment by orlp** [comment]
This is now implemented as `.get_disjoint_mut([K; N])`.

**Comment by michael-p** [comment]
Thank you!

**Pull request closed without merging**
