### PR TITLE
Add features

### PR DESCRIPTION
**Pull request by daiheitan**
It seems that you are missing features declaration in `Cargo.toml`

### CODE REVIEW

**Comment by daiheitan** [comment]
Oh, features are added as `serde`, explicit declaration is no more needed. Closing

**Comment by CGMossa** [comment]
This is cool, but shouldn't it be described somewhere?

**Comment by orlp** [comment]
@CGMossa Like here: https://docs.rs/slotmap/0.4.0/slotmap/#serialization-through-serde ?

**Comment by CGMossa** [comment]
I'm very sorry, this is very embarrassing. I'll delete my comment in 10 minutes. Thanks!

**Pull request closed without merging**
