### PR TITLE
Use separate value and key arrays

### PR DESCRIPTION
**Pull request by JoNil**
Hi!

Since, as far as i understand it, the goal of the dense slotmap is to have as fast iteration as possible over the values. It seems like a waste to have all that precious cache be filled with keys. So i built a version that uses separate vecs for the keys and the values. Something like what Mike Acton talks about in this talk: https://www.youtube.com/watch?v=rX0ItVEVjHc

It may not be what you want just did it because i felt like it. So if you want to merge this we should look at it carefully so i didn't break any invariant and probable do a couple of benchmarks to see if it actually makes any difference.

Cheers and nice job on the library the documentation is great!

### CODE REVIEW

**Comment by orlp** [comment]
I did mull over this exact decision, and decided to go with key-value pairs for simplicity of the implementation, and to avoid extra memory accesses when iterating over key-value pairs. I'll mull over it some more :)

**Comment by JoNil** [comment]
Please do :) Implementation wise it wasn't so bad, providing i got it right that is :P

When iterating over keys and values i have a feeling that the cpu will use two prefetch-streams to fetch the arrays efficiently.

Today i had the idea that we could also add get_value_slice, get_mut_value_slice, get_key_slice and get_mut_key_slice methods, for convenience :)

Cheers!

**Comment by orlp** [comment]
I'm most definitely not adding the slice functions *yet*, because they lock in a particular representation.

**Comment by JoNil** [comment]
Yepp that is a very good idea!

**Pull request merged**
